language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed project/udagram-api-feed
  - docker tag udagram-api-feed fable3/udagram-api-feed:latest
  - docker build -t udagram-api-user project/udagram-api-user
  - docker tag udagram-api-user fable3/udagram-api-user:latest
  - docker build -t udagram-reverse-proxy project/reverse-proxy
  - docker tag udagram-reverse-proxy fable3/udagram-reverse-proxy:latest
  - docker build -t udagram-frontend project/udagram-frontend
  - docker tag udagram-frontend fable3/udagram-frontend:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push fable3/udagram-api-user
  - docker push fable3/udagram-api-feed
  - docker push fable3/udagram-reverse-proxy
  - docker push fable3/udagram-frontend
