apiVersion: v1
kind: Service
metadata:
  name: udagram-frontend-svc
  labels:
    run: udagram-frontend-svc

spec:
  selector:
    run: udagram-frontend
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: LoadBalancer
  